name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - name: Build and run tests
      run: |
        npm ci
        npm run lint
        npm run es-check
        npm run ci:install-deps
        npm run test:gha
     
    - name: Run e2e tests
      run: |
        npm run e2e

    - name: Publish Coveralls report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
