name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    
    - name: Use Node.js
      uses: actions/setup-node
      with:
        node-version: '16.x'
    
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install-deps

    - name: Run checks
      run: |
        npm audit --only=prod --audit-level=moderate
        npm run lint
        npm run es-check
        npm run doc
        
    - name: Run tests
      run: |
        npm run test:gha
     
    - name: Run e2e tests
      run: |
        npm run start &
        npm run e2e

    - name: Publish Coveralls report
      uses: coverallsapp/github-action
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
